name: Update Literature Daily

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 更新到了 v4

      - name: Set up Python
        uses: actions/setup-python@v5 # 更新到了 v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python get-reference.py

- name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/data.json
          # 如果文件没变动，不要报错
          git commit -m "Auto-update: $(date)" || exit 0
          git push origin main
